# UYGULAMA AYARLARI

spring.application.name=internship-project-tmt
server.port=8080


# POSTGRESQL VERİTABANI BAĞLANTI AYARLARI

spring.datasource.url=jdbc:postgresql://localhost:5432/tmt_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


# HIBERNATE VE JPA AYARLARI

# Tabloları entity sınıflarına göre otomatik günceller
spring.jpa.hibernate.ddl-auto=update
# Çalıştırılan SQL sorgularını konsolda gösterir
spring.jpa.show-sql=true
# Konsoldaki SQL sorgularını okunabilir formata getirir
spring.jpa.properties.hibernate.format_sql=true


# HATA AYIKLAMA (DEBUG) AYARLARI

# Hata mesajlarını API yanıtlarına (ve Swagger'a) dahil eder
server.error.include-message=always
server.error.include-binding-errors=always